# MCP Server Configuration
# This configuration file adds the MCP server to the OpenHands configuration

# Include the MCP server in the configuration
[mcp]
# List of MCP SSE servers
sse_servers = [
    {
        # The URL of the MCP server
        url = "http://localhost:12000/mcp",
        # Optional API key for authentication (not required for local development)
        api_key = ""
    }
]

# List of MCP stdio servers (these will be started by the runtime)
stdio_servers = []